-- MySQL Script generated by MySQL Workbench
-- Thu Jul 27 12:29:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`insurance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`insurance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `conclusion_date` DATE NULL,
  `company` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `begin_date` DATE NULL,
  `end_date` DATE NULL,
  `fio` VARCHAR(100) NULL,
  `contract_number` VARCHAR(45) NULL,
  `vin` VARCHAR(45) NULL,
  `cost` INT NULL,
  `percentage` INT NULL,
  `payments_number` INT NULL,
  `kv1` INT NULL,
  `kv2` INT NULL,
  `signature_date1` DATE NULL,
  `signature_date2` DATE NULL,
  `payment_date1` DATE NULL,
  `payment_date2` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
